services:
    load-generator:
      build: 
        context: ./load-generator
        dockerfile: Dockerfile
        network: host
      container_name: load-generator
      network_mode: host
      devices:
          - /dev/kfd
          - /dev/dri    
      restart: unless-stopped
  