x-devices: &devices
    devices:
        - /dev/kfd
        - /dev/dri
    group_add:
        - video
x-defaults: &defaults
    security_opt:
        - seccomp:unconfined
    ipc: "host"
    shm_size: "128G"
    volumes:
      - ${CACHE_PATH}:/root/.cache/huggingface
    restart: on-failure      
    environment:
      HF_HOME: /root/.cache/huggingface   
      VLLM_USE_TRITON_FLASH_ATTN: 0
      TRUST_REMOTE_CODE: "true"
      VLLM_USE_V1: 0
      VLLM_USE_AITER: 1
      PYTORCH_HIP_ALLOC_CONF: expandable_segments:True      
    env_file:
      - .env

services:
  sglang-00:
    <<: [*defaults, *devices]
    image: $SGLANG_IMAGE
    command: python3 -m sglang.launch_server --model Qwen/Qwen3-14B --tp 2 --trust-remote-code --reasoning-parser deepseek-r1 --mem-fraction-static 0.8 --chunked-prefill-size 256 --port 9000
    network_mode: host
    environment:
      HIP_VISIBLE_DEVICES: "24,25"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/health"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 60s
      start_interval: 30s
    restart: on-failure
    profiles: ["sglang", "all", "default"]

  sglang-01:
    <<: [*defaults, *devices]
    image: $SGLANG_IMAGE
    command: python3 -m sglang.launch_server --model Qwen/Qwen3-14B --tp 2 --trust-remote-code --reasoning-parser deepseek-r1 --mem-fraction-static 0.8 --chunked-prefill-size 256 --port 9001
    network_mode: host
    environment:
      HIP_VISIBLE_DEVICES: "26,27"
    depends_on:
      sglang-00:
        condition: service_healthy      
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9001/health"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 60s
      start_interval: 30s
    restart: on-failure
    profiles: ["sglang", "all", "default"]

  sglang-02:
    <<: [*defaults, *devices]
    image: $SGLANG_IMAGE
    command: python3 -m sglang.launch_server --model Qwen/Qwen3-14B --tp 2 --trust-remote-code --reasoning-parser deepseek-r1 --mem-fraction-static 0.8 --chunked-prefill-size 256 --port 9002
    network_mode: host
    environment:
      HIP_VISIBLE_DEVICES: "28,29"
    depends_on:
      sglang-01:
        condition: service_healthy         
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9002/health"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 60s
      start_interval: 30s
    restart: on-failure
    profiles: ["sglang", "all", "default"]

  sglang-03:
    <<: [*defaults, *devices]
    image: $SGLANG_IMAGE
    command: python3 -m sglang.launch_server --model Qwen/Qwen3-14B --tp 2 --trust-remote-code --reasoning-parser deepseek-r1 --mem-fraction-static 0.8 --chunked-prefill-size 256 --port 9003
    network_mode: host
    environment:
      HIP_VISIBLE_DEVICES: "30,31"
    depends_on:
      sglang-02:
        condition: service_healthy         
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9002/health"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 60s
      start_interval: 30s
    restart: on-failure
    profiles: ["sglang", "all", "default"]