x-devices: &devices
    devices:
        - /dev/kfd
        - /dev/dri
    group_add:
        - video
x-defaults: &defaults
    security_opt:
        - seccomp:unconfined
    ipc: "host"
    shm_size: "64G"
    ulimits:
      memlock: 2147483648
      stack: 2147483648

services:
  sglang:
    <<: [*defaults, *devices]
    image: $SGLANG_IMAGE
    command: python3 -m sglang.launch_server --model deepseek-ai/DeepSeek-R1-Distill-Llama-70B --tp 8 --trust-remote-code --expert-parallel-size 1 --reasoning-parser deepseek-r1 --port 9000
    network_mode: host
    volumes:
      - /data2/hf_home:/root/.cache/huggingface
      - /data2/torchinductor_cache:/torchinductor_cache
    environment:
      HIP_VISIBLE_DEVICES: "16,17,18,19,20,21,22,23"
      PYTORCH_HIP_ALLOC_CONF: expandable_segments:True
    ipc: host
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/health"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 60s
      start_interval: 30s
    restart: on-failure
    env_file: 
      - .env
