# Main docker-compose file that includes all other compose files
name: ai-infra-summit

include:
  - path: docker-compose.vllm.yaml
  - path: docker-compose.sglang.yaml
  - path: docker-compose.litellm.yaml
  - path: docker-compose.load-generator.yaml

# Define a default service so "docker compose up -d" works without specifying services
services:
  default:
    image: busybox
    command: echo "Starting all services via dependencies"
    profiles: ["all", "default"]
    depends_on:
      # List all top-level services that should start by default
      - proxy
      # Add dependencies for each model group
      - vllm-model0  # qwen3-4b group
      - vllm-model4  # qwen2.5-7b group
      - vllm-model8  # phi-4-mini group
      - vllm-model12 # mistral-nemo group
      - vllm-model16 # bge-embeddings group
      - vllm-model20 # bge-reranker group
      - sglang-00    # sglang group