include:
  - path: docker-compose.vllm.yaml
  - path: docker-compose.sglang.yaml
  - path: docker-compose.litellm.yaml
  - path: docker-compose.load-generator.yaml

# Define a default service so "docker compose up -d" works without specifying services
services:
  default:
    image: busybox
    command: echo "Starting all services via dependencies"
    network_mode: host
    depends_on:
      - proxy
      - vllm-model0  # qwen3-4b group
      - vllm-model4  # qwen2.5-7b group
      - vllm-model8  # phi-4-mini group
      - vllm-model12 # mistral-nemo group
      - vllm-model16 # bge-embeddings group
      - vllm-model20 # bge-reranker group
      - sglang-00    # sglang group